title: Dagstuhl 23022 

author:
    name: Andreas Mang
    email: andreas@math.uh.edu

description: >
    Webspace curating research efforts related to the Dagstuhl Seminar 23022 "Inverse Biophysical Modeling and Machine Learning in Personalized Oncology". 

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
